<?php
$Abulan = array(
        'Januari' =>'01',
        'Februari' =>'02',
        'Maret' =>'03',
        'April' =>'04',
        'Mei' =>'05',
        'Juni' =>'06',
        'Juli' =>'07',
        'Agustus'=>'08',
        'September' =>'09',
        'Oktober' =>'10',
        'November' =>'11',
        'Desember' =>'12');
    $ANbulan = array(
            1=>'Januari',
            2=>'Februari',
            3=>'Maret',
            4=>'April',
            5=>'Mei',
            6=>'Juni',
            7=>'Juli',
            8=>'Agustus',
            9=>'September',
            10=>'Oktober',
            11=>'November',
            12=>'Desember' );
    
    $bbulan = array(
            '01'=>'Januari',
            '02'=>'Februari',
            '03'=>'Maret',
            '04'=>'April',
            '05'=>'Mei',
            '06'=>'Juni',
            '07'=>'Juli',
            '08'=>'Agustus',
            '09'=>'September',
            '10'=>'Oktober',
            '11'=>'November',
            '12'=>'Desember' );
?>